<#
.SYNOPSIS
Safely archives and cleans Windows Event Logs with dry run, logging, summary, rollback metadata, and idempotent daily archives.

.DESCRIPTION
Cleanup mode:
- Targets only logs whose newest event is older than a configurable number of days.
- Supports dry run and prints the number of records that would be deleted.
- Archives eligible logs to .evtx files before clearing.
- Uses per-operation try/catch so one failure does not stop the run.
- Writes a timestamped action log and a rollback manifest.
- Skips archive/clear for logs already archived today (idempotent behavior).

Rollback mode:
- Uses the manifest from a cleanup run.
- Restores archived/backup .evtx files into a restore folder for investigation.
- Note: Windows Event Log channels do not support safe in-place re-import of events.

Designed for Windows PowerShell 5.1.
#>

[CmdletBinding(DefaultParameterSetName = 'Cleanup')]
param(
    # Cleanup mode: only logs older than this many days are eligible.
    [Parameter(ParameterSetName = 'Cleanup')]
    [ValidateRange(1, 3650)]
    [int]$OlderThanDays = 3,

    # Cleanup mode: if set, report what would be deleted but do not archive/clear.
    [Parameter(ParameterSetName = 'Cleanup')]
    [switch]$DryRun,

    # Cleanup mode: optional list of log names to process. If omitted, all enabled logs are evaluated.
    [Parameter(ParameterSetName = 'Cleanup')]
    [string[]]$LogNames = @(),

    # Rollback mode: path to a manifest CSV generated by a prior cleanup run.
    [Parameter(ParameterSetName = 'Rollback', Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$RollbackManifestPath,

    # Rollback mode: if set, report what would be restored but do not copy files.
    [Parameter(ParameterSetName = 'Rollback')]
    [switch]$RollbackDryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Section 1: Initialize run metadata and working folders.
# This section builds timestamped paths for logs, archives, rollback artifacts, and restore output.
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$todayStamp = Get-Date -Format 'yyyyMMdd'

$logDir = Join-Path $scriptRoot 'logs'
$archiveRoot = Join-Path $scriptRoot 'eventlog-archive'
$rollbackRoot = Join-Path $scriptRoot 'rollback'
$restoreRoot = Join-Path $rollbackRoot ('eventlog_restore_{0}' -f $timestamp)

$logPath = Join-Path $logDir ('eventlog_cleanup_{0}.log' -f $timestamp)
$manifestPath = Join-Path $rollbackRoot ('eventlog_manifest_{0}.csv' -f $timestamp)

foreach ($dir in @($logDir, $archiveRoot, $rollbackRoot)) {
    try {
        if (-not (Test-Path -LiteralPath $dir)) {
            New-Item -Path $dir -ItemType Directory -Force | Out-Null
        }
    }
    catch {
        throw "Failed to create required directory '$dir'. Error: $($_.Exception.Message)"
    }
}

# Section 2: Central logging helper.
# This section logs every action to console and a timestamped log file.
function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level,

        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Write-Output $line

    try {
        Add-Content -LiteralPath $logPath -Value $line -ErrorAction Stop
    }
    catch {
        Write-Output ('[{0}] [ERROR] Failed writing to log file: {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $_.Exception.Message)
    }
}

# Section 3: Utility helpers.
# This section provides safe filename conversion and native wevtutil invocation wrappers.
function Convert-LogNameToSafeFileName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LogName
    )

    $safe = $LogName -replace '[^a-zA-Z0-9_.-]', '_'
    if ([string]::IsNullOrWhiteSpace($safe)) {
        return 'unnamed_log'
    }

    return $safe
}

function Invoke-Wevtutil {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [Parameter(Mandatory = $true)]
        [string]$OperationName
    )

    try {
        $output = & wevtutil.exe @Arguments 2>&1
        if ($LASTEXITCODE -ne 0) {
            $joinedOutput = ($output | Out-String).Trim()
            throw "wevtutil failed for $OperationName with exit code $LASTEXITCODE. Output: $joinedOutput"
        }

        return $output
    }
    catch {
        throw "Operation '$OperationName' failed. Error: $($_.Exception.Message)"
    }
}

# Section 4: Event log query helpers.
# This section gathers newest event times and record counts with isolated error handling.
function Get-NewestEventTime {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LogName
    )

    try {
        $event = Get-WinEvent -LogName $LogName -MaxEvents 1 -ErrorAction Stop
        if ($null -eq $event) {
            return $null
        }

        return $event.TimeCreated
    }
    catch {
        throw "Could not read newest event for '$LogName'. Error: $($_.Exception.Message)"
    }
}

function Get-RecordCountOlderThan {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LogName,

        [Parameter(Mandatory = $true)]
        [datetime]$Cutoff
    )

    try {
        $count = (Get-WinEvent -FilterHashtable @{ LogName = $LogName; EndTime = $Cutoff } -ErrorAction Stop | Measure-Object).Count
        return [int]$count
    }
    catch {
        throw "Could not count records older than cutoff for '$LogName'. Error: $($_.Exception.Message)"
    }
}

function Get-TotalRecordCount {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LogName
    )

    try {
        $cfg = Get-WinEvent -ListLog $LogName -ErrorAction Stop
        return [int]$cfg.RecordCount
    }
    catch {
        throw "Could not get total record count for '$LogName'. Error: $($_.Exception.Message)"
    }
}

# Section 5: Cleanup mode.
# This section evaluates eligible logs, performs dry run reporting, archives, clears, and writes a rollback manifest.
if ($PSCmdlet.ParameterSetName -eq 'Cleanup') {
    Write-Log -Level 'INFO' -Message 'Starting cleanup mode.'

    $cutoff = (Get-Date).AddDays(-$OlderThanDays)
    Write-Log -Level 'INFO' -Message ("Cutoff time: {0}" -f $cutoff)

    $stats = [ordered]@{
        Mode = 'Cleanup'
        OlderThanDays = $OlderThanDays
        LogsEvaluated = 0
        LogsEligible = 0
        LogsArchived = 0
        LogsCleared = 0
        LogsSkippedRecent = 0
        LogsSkippedIdempotent = 0
        LogsSkippedEmpty = 0
        LogsSkippedErrors = 0
        RecordsToDeleteDryRun = 0
        RecordsDeleted = 0
    }

    $manifestRows = New-Object System.Collections.Generic.List[object]

    $sourceLogs = @()
    try {
        if ($LogNames.Count -gt 0) {
            foreach ($name in $LogNames) {
                try {
                    $cfg = Get-WinEvent -ListLog $name -ErrorAction Stop
                    $sourceLogs += $cfg
                }
                catch {
                    $stats.LogsSkippedErrors++
                    Write-Log -Level 'ERROR' -Message ("Requested log not available: {0}. Error: {1}" -f $name, $_.Exception.Message)
                }
            }
        }
        else {
            $sourceLogs = Get-WinEvent -ListLog * -ErrorAction Stop | Where-Object { $_.IsEnabled }
        }
    }
    catch {
        throw "Failed to enumerate event logs. Error: $($_.Exception.Message)"
    }

    foreach ($log in $sourceLogs) {
        $stats.LogsEvaluated++
        $logName = [string]$log.LogName
        $safeName = Convert-LogNameToSafeFileName -LogName $logName

        Write-Log -Level 'INFO' -Message ("Evaluating log: {0}" -f $logName)

        try {
            $totalCount = Get-TotalRecordCount -LogName $logName
            if ($totalCount -le 0) {
                $stats.LogsSkippedEmpty++
                Write-Log -Level 'INFO' -Message ("Skipping empty log: {0}" -f $logName)
                continue
            }

            $newestTime = Get-NewestEventTime -LogName $logName
            if ($null -eq $newestTime) {
                $stats.LogsSkippedEmpty++
                Write-Log -Level 'INFO' -Message ("Skipping log with no events: {0}" -f $logName)
                continue
            }

            if ($newestTime -gt $cutoff) {
                $stats.LogsSkippedRecent++
                Write-Log -Level 'INFO' -Message ("Skipping log with recent records: {0} (Newest: {1})" -f $logName, $newestTime)
                continue
            }

            $stats.LogsEligible++

            $archivePath = Join-Path $archiveRoot ('{0}_{1}.evtx' -f $safeName, $todayStamp)
            $rollbackBackupPath = Join-Path $rollbackRoot ('{0}_{1}.evtx' -f $safeName, $timestamp)

            if ($DryRun) {
                $olderCount = Get-RecordCountOlderThan -LogName $logName -Cutoff $cutoff
                $stats.RecordsToDeleteDryRun += $olderCount
                Write-Log -Level 'INFO' -Message ("DRYRUN eligible log: {0}; records to delete: {1}" -f $logName, $olderCount)
                continue
            }

            if (Test-Path -LiteralPath $archivePath) {
                $stats.LogsSkippedIdempotent++
                Write-Log -Level 'INFO' -Message ("Idempotent skip: archive for today already exists: {0}" -f $archivePath)
                continue
            }

            try {
                Invoke-Wevtutil -Arguments @('epl', $logName, $archivePath, '/ow:false') -OperationName ("Archive {0}" -f $logName) | Out-Null
                $stats.LogsArchived++
                Write-Log -Level 'INFO' -Message ("Archived log: {0} -> {1}" -f $logName, $archivePath)
            }
            catch {
                $stats.LogsSkippedErrors++
                Write-Log -Level 'ERROR' -Message ("Archive failed for {0}. Error: {1}" -f $logName, $_.Exception.Message)
                continue
            }

            try {
                Invoke-Wevtutil -Arguments @('cl', $logName, ("/bu:{0}" -f $rollbackBackupPath)) -OperationName ("Clear {0}" -f $logName) | Out-Null
                $stats.LogsCleared++
                $stats.RecordsDeleted += $totalCount
                Write-Log -Level 'INFO' -Message ("Cleared log: {0}; rollback backup: {1}" -f $logName, $rollbackBackupPath)

                $manifestRows.Add([pscustomobject]@{
                    LogName = $logName
                    ArchivePath = $archivePath
                    RollbackBackupPath = $rollbackBackupPath
                    ClearedRecordCount = $totalCount
                    NewestEventTime = $newestTime
                    CutoffUsed = $cutoff
                    ActionTime = (Get-Date)
                }) | Out-Null
            }
            catch {
                $stats.LogsSkippedErrors++
                Write-Log -Level 'ERROR' -Message ("Clear failed for {0}. Error: {1}" -f $logName, $_.Exception.Message)
                continue
            }
        }
        catch {
            $stats.LogsSkippedErrors++
            Write-Log -Level 'ERROR' -Message ("Evaluation failed for {0}. Error: {1}" -f $logName, $_.Exception.Message)
            continue
        }
    }

    if (-not $DryRun) {
        try {
            $manifestRows | Export-Csv -LiteralPath $manifestPath -NoTypeInformation -Encoding UTF8
            Write-Log -Level 'INFO' -Message ("Rollback manifest created: {0}" -f $manifestPath)
        }
        catch {
            Write-Log -Level 'ERROR' -Message ("Failed to write rollback manifest. Error: {0}" -f $_.Exception.Message)
        }
    }

    # Section 6: Cleanup summary.
    # This section prints a run summary including deletion counts and output file locations.
    Write-Output ''
    Write-Output '=== Event Log Cleanup Summary ==='
    $stats.GetEnumerator() | ForEach-Object { Write-Output ("{0}: {1}" -f $_.Key, $_.Value) }
    Write-Output ("LogFile: {0}" -f $logPath)

    if (-not $DryRun) {
        Write-Output ("ArchiveFolder: {0}" -f $archiveRoot)
        Write-Output ("ManifestFile: {0}" -f $manifestPath)
    }

    return
}

# Section 7: Rollback mode.
# This section restores archived and pre-clear backup files to a restore folder based on manifest metadata.
if ($PSCmdlet.ParameterSetName -eq 'Rollback') {
    Write-Log -Level 'INFO' -Message 'Starting rollback mode.'
    Write-Log -Level 'INFO' -Message ("Manifest path: {0}" -f $RollbackManifestPath)

    if (-not (Test-Path -LiteralPath $RollbackManifestPath)) {
        throw "Rollback manifest not found: $RollbackManifestPath"
    }

    $stats = [ordered]@{
        Mode = 'Rollback'
        RowsRead = 0
        RestoredFiles = 0
        DryRunListed = 0
        MissingFiles = 0
        Errors = 0
    }

    try {
        $rows = Import-Csv -LiteralPath $RollbackManifestPath -ErrorAction Stop
    }
    catch {
        throw "Failed to read rollback manifest. Error: $($_.Exception.Message)"
    }

    if (-not $RollbackDryRun) {
        try {
            if (-not (Test-Path -LiteralPath $restoreRoot)) {
                New-Item -Path $restoreRoot -ItemType Directory -Force | Out-Null
            }
        }
        catch {
            throw "Failed to create restore folder '$restoreRoot'. Error: $($_.Exception.Message)"
        }
    }

    foreach ($row in $rows) {
        $stats.RowsRead++

        $logName = [string]$row.LogName
        $archivePath = [string]$row.ArchivePath
        $backupPath = [string]$row.RollbackBackupPath

        try {
            foreach ($source in @($archivePath, $backupPath)) {
                if ([string]::IsNullOrWhiteSpace($source)) {
                    continue
                }

                if (-not (Test-Path -LiteralPath $source)) {
                    $stats.MissingFiles++
                    Write-Log -Level 'WARN' -Message ("Rollback source missing for log {0}: {1}" -f $logName, $source)
                    continue
                }

                $target = Join-Path $restoreRoot (Split-Path -Leaf $source)

                if ($RollbackDryRun) {
                    $stats.DryRunListed++
                    Write-Output ("Would restore file: {0} -> {1}" -f $source, $target)
                    Write-Log -Level 'INFO' -Message ("DRYRUN would restore file: {0} -> {1}" -f $source, $target)
                    continue
                }

                try {
                    Copy-Item -LiteralPath $source -Destination $target -Force -ErrorAction Stop
                    $stats.RestoredFiles++
                    Write-Log -Level 'INFO' -Message ("Restored file: {0} -> {1}" -f $source, $target)
                }
                catch {
                    $stats.Errors++
                    Write-Log -Level 'ERROR' -Message ("Failed to restore file {0}. Error: {1}" -f $source, $_.Exception.Message)
                }
            }
        }
        catch {
            $stats.Errors++
            Write-Log -Level 'ERROR' -Message ("Rollback processing failed for log {0}. Error: {1}" -f $logName, $_.Exception.Message)
        }
    }

    # Section 8: Rollback summary.
    # This section prints rollback results and points to the restore folder and run log.
    Write-Output ''
    Write-Output '=== Event Log Rollback Summary ==='
    $stats.GetEnumerator() | ForEach-Object { Write-Output ("{0}: {1}" -f $_.Key, $_.Value) }
    Write-Output ("LogFile: {0}" -f $logPath)

    if (-not $RollbackDryRun) {
        Write-Output ("RestoreFolder: {0}" -f $restoreRoot)
    }

    Write-Output ''
    Write-Output 'Note: Windows Event Log channels do not support safe direct re-import of events into live logs.'
    Write-Output 'Rollback mode restores exported evidence files for investigation and retention.'

    return
}
